# -*- coding: utf-8 -*-
"""utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-3mN67IreDibvyitEy5L2voCzrqcW4tF
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Generator, Iterable, Optional, Set


class InputCancelled(Exception):
    pass


class InvalidInput(Exception):
    pass



def safe_input(prompt: str) -> str:
    try:
        return input(prompt)
    except (KeyboardInterrupt, EOFError) as e:
        raise InputCancelled from e


def prompt_choice(prompt: str, valid: Set[str]) -> str:
    while True:
        try:
            s: str = safe_input(prompt).strip()
            if s not in valid:
                raise InvalidInput
            return s
        except InvalidInput:
            print("잘못된 입력입니다.")
        except InputCancelled:
            raise


def prompt_text(prompt: str, *, allow_cancel: bool = False) -> Optional[str]:
    while True:
        try:
            s: str = safe_input(prompt).strip()
            if allow_cancel and s.lower() == "q":
                return None
            if not s:
                raise InvalidInput
            return s
        except InvalidInput:
            print("잘못된 입력입니다.")
        except InputCancelled:
            raise



def iter_lines(lines: Iterable[str]) -> Generator[str, None, None]:
    for line in lines:
        yield line


@dataclass(frozen=True)
class Messages:
    APP_TITLE: str = "==== RPG CLI ===="
    MENU_MAIN: str = (
        "1) 맵 진입(채집+전투)\n"
        "2) 상태 보기\n"
        "3) 인벤토리 보기\n"
        "4) 장비 관리\n"
        "5) 종료"
    )
    MENU_BATTLE: str = "1) 공격  2) 포션 사용  3) 도망"
    MENU_EQUIP: str = "1) 장착  2) 해제(weapon)  3) 해제(armor)  4) 뒤로"

    EXIT: str = "프로그램 종료."
    INTERRUPTED: str = "입력이 중단되었습니다. 즉시 종료합니다."
    INVALID_INPUT: str = "잘못된 입력입니다."
    CANCELLED: str = "취소되었습니다."

    GATHER_NONE: str = "아무 것도 발견하지 못했다..."
    GATHER_SUCCESS: str = "채집 성공!"
    ESCAPE: str = "도망쳤다! 전투 종료."
    DEFEAT: str = "패배... (HP가 0이 되었습니다)"
    POTION_USED: str = "포션 사용! HP 회복."
    NO_POTION: str = "포션이 없다!"
    INV_EMPTY: str = "비어 있음."