# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D-VDy8JqGXG3DE9fmDT8YHQ5vf76wSGb
"""

from __future__ import annotations

import asyncio
from game import run_game


def main() -> None:
    asyncio.run(run_game())


if __name__ == "__main__":
    main()